### ISSUE TITLE
Password Security 

### ISSUE THREAD

**Issue by LuaTenshi** [aegamesi/SteamTrade#1]
I am sure you have gotten many questions regarding your apps security, but that is probably because it's not very well known. I have two questions, why can't we just have it open a Web page were we can login to steam securely? Also if I wanted to rebuild this app without the trading features and where looking to enhance the chat experience, where would I start?

**Comment by aegamesi** [comment]
By "open a Web page" I assume you're referring to either OpenID or Steam
Web. OpenID (what you use to log on to backpack.tf, for example) is merely
authentication. It provides no access to account features, like trading or
chatting (this is a good thing). Steam Web would only allow access to
certain features: most of them at this point, but not all of them.
Furthermore, this wouldn't be too much more secure: the app would still
have access to your username, password, and access tokens. Ice works by
fully emulating a Steam client via Steamkit, allowing the possibility for
more features, at the cost of requiring a username and password.

As for your second question, I do not know. SteamKit would, of course, be
an excellent start. Keep in mind, however, that the source code of Ice is
provided for reference only, and cannot be distributed in a modified form.

What chat enhancements were you thinking about? Perhaps they could be
integrated into Ice.

-ae

**Comment by LuaTenshi** [comment]
Was thinking about supporting emoticons in chat (if they are not already supported). Its become quite a trend with allot of users on Steam, so I thought it would be cool.

Also since using a login through a webpage would limit the application, I suggest making it more clear that the login is for Steam authentication only. Not sure how you would be able to do that but it is something to think about.

I would love to see Ice become a go to client for Steam chat, because honestly the default phone app is so old at this point that it not only uses unnecessary battery power but also has glitches and bugs everywhere.
