### ISSUE TITLE
No Gradle Files

### ISSUE THREAD

**Issue by hendrikbl** [aegamesi/SteamTrade#11]
Hey,
I wanted to see if i can do something to improve some UI related things. But after I forked the repo and wanted to open it in AndroidStudio, I noticed the .gradle files are missing, what makes working with it impossible... :(

Could you add these files to your repo or isn't this repo meant for contributing? :)

**Comment by aegamesi** [comment]
This repo isn't exactly meant for contributing -- it's more so people can view the source code of Ice.

If you're seriously interested in contributing, I can try to help you get the project set up (with Gradle and all) at some point. I am very busy for the next week or so, however.

**Comment by hendrikbl** [comment]
Okay, then never mind :)
I just wanted to see if i can so some small things here and there, nothing too serious.
