### ISSUE TITLE
app crashes when i opening trade notifications (if i have an trade)

### ISSUE THREAD

**Issue by EgoruOfficial** [aegamesi/SteamTrade#13]

**Comment by aegamesi** [comment]
Can you post a link to your steam profile and information about your phone? (Device manufacturer and model, Android version)

**Comment by EgoruOfficial** [comment]
link - steamcommunity.com/id/egoruofficial
Android 7.1.2 (custom), LG Nexus 4

**Comment by EgoruOfficial** [comment]
![image](https://cloud.githubusercontent.com/assets/23292145/25307112/1c3e4452-27a4-11e7-8a84-c6e563d3bdc0.png)

**Comment by EgoruOfficial** [comment]
so?

**Comment by aegamesi** [comment]
I've been incredibly busy recently, it's going to take a bit of time to try to resolve your issue.

**Comment by EgoruOfficial** [comment]
ok. i translating app to russian lang now.

**Comment by EgoruOfficial** [comment]
and?

**Comment by EgoruOfficial** [comment]
Fixed at now.
