### ISSUE TITLE
Build SteamKit

### ISSUE THREAD

**Issue by FabianTerhorst** [aegamesi/SteamTrade#4]
Hello,

i tried to build the project, included all jars, but it looks like the steamkit on the repository https://github.com/aegamesi/SteamKit-Java isn´t the version that used in the client repo. Its would be nice if you update your steamkit repo.

**Comment by aegamesi** [comment]
Updated. Unfortunately, I must have auto formatted the code at some point, so the commit is rather messy. All the code is there, however.

**Comment by FabianTerhorst** [comment]
thank you, it works now.
