### ISSUE TITLE
Build SteamKit  error

### ISSUE THREAD

**Issue by JeromeHuang** [aegamesi/SteamTrade#9]
hi，I import the SteamKit-java project. However, there're many errors. Like this problem as follows:
Builder cannot be resolved to a type ClientMsgProtobuf.java /steamkit/src/main/java/uk/co/thomasc/steamkit/base line 112 Java Problem

I use jdk1.7. It seems that these problems relates to the Proto-Buf. How can I fix the problem?
The project doesn't update for a long time. I wonder if the project can still work.

**Comment by aegamesi** [comment]
Issues with SteamKit-Java do not belong here.

**Comment by JeromeHuang** [comment]
Thanks. Could you tell me how to have the  Java Protobuf library for SteamKit-Java to work?
I have always import the Protobuf  dependency. I have been negged for several days. Please help me!
Thank you!

**Comment by aegamesi** [comment]
Are you using Gradle?

**Comment by JeromeHuang** [comment]
NO. I use eclipse. I find the error. I don't import the file proto.jar in 'src'.

**Comment by JeromeHuang** [comment]
No, I use eclipse. I don't modify any code. I wonder why there're so many errors. Should I import some other jars except the maven dependencies or install some other tools in eclipse.

**Comment by aegamesi** [comment]
I don't personally use Eclipse, but you need to have both Lombok (I believe there's an Eclipse plugin) and Protobuf added to your project libraries.

**Comment by JeromeHuang** [comment]
I have already addthe lombok.jar and proto.jar to the project. Should I install relative tools?

**Comment by JeromeHuang** [comment]
I fix the problem. The  http://top-cat.github.com/SteamKit-Java project could work well after install Lombok  plugin. Thanks.
However, I find that the project https://github.com/aegamesi/SteamKit-Java of yours takes a long time to build.The top-cat's project builds quickly. That's strange.
